fragment UserFragment on User {
  id
  name
  lastName
  email
  username
  birthdate
  createdAt
  updatedAt
}

mutation RegisterAccount($input: AccountRegisterInput!) {
  accountRegister(input: $input) {
    user {
      ...UserFragment
    }
  }
}
